# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondaryGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(350, 500)
        SecondWindow.setMinimumSize(QtCore.QSize(350, 500))
        SecondWindow.setMaximumSize(QtCore.QSize(350, 500))
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OutfrontLogo = QtWidgets.QLabel(self.centralwidget)
        self.OutfrontLogo.setGeometry(QtCore.QRect(40, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setItalic(True)
        font.setUnderline(False)
        self.OutfrontLogo.setFont(font)
        self.OutfrontLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.OutfrontLogo.setObjectName("OutfrontLogo")
        self.ReservationButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReservationButton.setGeometry(QtCore.QRect(90, 360, 170, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ReservationButton.setFont(font)
        self.ReservationButton.setObjectName("ReservationButton")
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel.setGeometry(QtCore.QRect(150, 100, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.NameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.NameInput.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.NameInput.setObjectName("NameInput")
        self.NumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.NumberLabel.setGeometry(QtCore.QRect(100, 180, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumberLabel.setFont(font)
        self.NumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NumberLabel.setObjectName("NumberLabel")
        self.PhoneLabel = QtWidgets.QLabel(self.centralwidget)
        self.PhoneLabel.setGeometry(QtCore.QRect(120, 270, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PhoneLabel.setFont(font)
        self.PhoneLabel.setObjectName("PhoneLabel")
        self.PhoneInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PhoneInput.setGeometry(QtCore.QRect(120, 290, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PhoneInput.setFont(font)
        self.PhoneInput.setText("")
        self.PhoneInput.setObjectName("PhoneInput")
        self.PhoneInput.setMaxLength(10)
        self.PhoneInput.setValidator(QtGui.QIntValidator())
        self.NumberInput = QtWidgets.QLineEdit(self.centralwidget)
        self.NumberInput.setGeometry(QtCore.QRect(120, 200, 113, 20))
        self.NumberInput.setObjectName("NumberInput")
        self.NumberInput.setMaxLength(2)
        self.NumberInput.setValidator(QtGui.QIntValidator())
        self.ReservationLogo = QtWidgets.QLabel(self.centralwidget)
        self.ReservationLogo.setGeometry(QtCore.QRect(100, 50, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setItalic(True)
        self.ReservationLogo.setFont(font)
        self.ReservationLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.ReservationLogo.setObjectName("ReservationLogo")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "New Reservation"))
        self.OutfrontLogo.setText(_translate("SecondWindow", "Outfront Steakhouse"))
        self.ReservationButton.setText(_translate("SecondWindow", "Create Reservation"))
        self.NameLabel.setText(_translate("SecondWindow", "Name:"))
        self.NumberLabel.setText(_translate("SecondWindow", "Number of People:"))
        self.PhoneLabel.setText(_translate("SecondWindow", "Phone Number:"))
        self.ReservationLogo.setText(_translate("SecondWindow", "Reservation Creator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
